import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import LayoutDefault from "@/components/layout/layout-default";
import Topbar from "@/components/topNav";

const font = DM_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={font.className}>
        <LayoutDefault className="bg-muted/50 py-[6rem] ">
        <Topbar/>
        {children}
        </LayoutDefault>
      </body>
    </html>
  );
}
